spring:
  application:
    name: User
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${HOST_KEYCLOAK_URI}
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
keycloak:
  host: ${HOST_KEYCLOAK}
  host-admin: ${HOST_KEYCLOAK_ADMIN}
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
server:
  port: 8082
  url: ${SERVER_URL}
minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  secure: false
  get-url: ${MINIO_GET_URL}
